modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
  modId="example"
  version="${file.jarVersion}"
  displayName="Example"
  # updateJSONURL="https://change.me.example.invalid/updates.json"
  # displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
  logoFile="example.png"
  authors="andante."
  # credits="Thanks for this example mod goes to Java"

  description='''

  '''

[[dependencies.example]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.example]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
